#!/bin/sh

service_name="gamelog-headless.service"
headless_was_active=0
cleanup_done=0

if systemctl --user is-active --quiet "$service_name"; then
    headless_was_active=1
    systemctl --user stop "$service_name" || exit $?
fi

cleanup()
{
    status=$?

    if [ "$cleanup_done" -eq 0 ]; then
        cleanup_done=1

        if [ "$headless_was_active" -eq 1 ]; then
            systemctl --user start "$service_name"
        fi
    fi

    trap - EXIT HUP INT TERM
    exit "$status"
}

trap cleanup EXIT HUP INT TERM

/usr/bin/gamelog --gui
