#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(gamelogCoreLog)
Q_DECLARE_LOGGING_CATEGORY(gamelogAgentLog)
Q_DECLARE_LOGGING_CATEGORY(gamelogGuiLog)
Q_DECLARE_LOGGING_CATEGORY(gamelogDatabaseLog)
Q_DECLARE_LOGGING_CATEGORY(gamelogIpcLog)
